### ISSUE TITLE
pip install nagare failure

### ISSUE THREAD

**Issue by jpic** [nagareproject/core#10]
Hello !

Nice framework ! But i can't install:

$ pypy --version
Python 2.7.13 (0e7ea4fe15e82d5124e805e2e4a37cae1a402d4b, Jan 29 2018, 16:21:45)
[PyPy 5.10.0 with GCC 7.2.1 20180116]

$ pypyenv/bin/pip install nagare[full]
Collecting nagare[full]
  Using cached nagare-0.5.1.tar.gz
Collecting PEAK-Rules (from nagare[full])
  Could not find a version that satisfies the requirement PEAK-Rules (from nagare[full]) (from versions: )
No matching distribution found for PEAK-Rules (from nagare[full])

Also tryied with the compiled stackless python. 

Any clue welcome

**Comment by nagareproject** [comment]
Hi,

As `pip` and `easy_install` algos to fetch packages differ, the `PEAK-Rules` dependency can't be installed with `pip`. And so is Nagare.

You must use `easy_install`:

```
$ pypyenv/bin/easy_install "nagare[full]"
```

See http://www.nagare.org/core/quickstart.html

Best regards
