### ISSUE TITLE
Unexpected results when using a Tag instance more than once

### ISSUE THREAD

**Issue by bcroq** [nagareproject/core#11]
```python
from nagare.namespaces import xhtml

h = xhtml.Renderer()

el = h.div('1', h.span('span'), '2', h.span('span'), '3')
print el.write_xmlstring()

span = h.span('span')
el = h.div('1', span, '2', span, '3')
print el.write_xmlstring()
```
I would expect to get the same same string twice but instead the first one prints `<div>1<span>span</span>2<span>span</span>3</div>` (as expected) whereas the second one prints`<div>1<span>span</span>23</div>`.

**Comment by nagareproject** [comment]
This is the expected behavior as you're trying to attach the same `span('span')` element several time to different parents. A DOM element can only appear once in a document.
