### ISSUE TITLE
StackLess Python no longer maintained

### ISSUE THREAD

**Issue by hazho** [nagareproject/core#12]
What would be the future of nagare framework?

I was thinking of building something like this using Stackless python, but came to my mind to see the repo of it, and it is no longer maintained, so, it would be useless to take efforts while the future of Nagare is Not Known (not sustainable), am I wrong?

I would like to know the opinions from the core developers, before I decide my next steps

**Comment by nagareproject** [comment]
Hi Hazho,

Since november 2023, Nagare doesn't need Stackless Python anymore for the continuation : https://github.com/nagareproject/core/commit/af5d74e1f2f3096cc31662cbcc6e96ab001fd73a deployed in production.

Nagare works now with CPython >= 3.10 (and very soon 3.13 ;)

**Comment by hazho** [comment]
then how to install? can you please update the official documentations?
